#ifndef PRODUCER_T_I_PRODUCER_PRODUCER_API_H
#define PRODUCER_T_I_PRODUCER_PRODUCER_API_H

#include <all.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void api_put_emit__base_test_event_port_periodic_domains_producer_t_i_producer_producer(STACK_FRAME_ONLY);

void api_logInfo__base_test_event_port_periodic_domains_producer_t_i_producer_producer(
  STACK_FRAME
  String str);

void api_logDebug__base_test_event_port_periodic_domains_producer_t_i_producer_producer(
  STACK_FRAME
  String str);

void api_logError__base_test_event_port_periodic_domains_producer_t_i_producer_producer(
  STACK_FRAME
  String str);

#endif
