// #Sireum

package base.test_data_port_periodic_domains

import org.sireum._
import art._
import base._
import base.test_data_port_periodic_domains.{consumer_thread_i_consumer_consumer => component}

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@datatype class consumer_thread_i_consumer_consumer_Bridge(
  val id: Art.BridgeId,
  val name: String,
  val dispatchProtocol: DispatchPropertyProtocol,
  val dispatchTriggers: Option[ISZ[Art.PortId]],

  read_port: Port[Base_Types.Integer_8]
  ) extends Bridge {

  val ports : Bridge.Ports = Bridge.Ports(
    dataIns = ISZ[art.UPort](read_port),

    dataOuts = ISZ[art.UPort](),

    eventIns = ISZ[art.UPort](),

    eventOuts = ISZ[art.UPort]()
  )

  val initialization_api : consumer_thread_i_Initialization_Api = {
    val api = consumer_thread_i_Initialization_Api(
      id,
      read_port.id
    )
    consumer_thread_i_consumer_consumer_Bridge.c_initialization_api = Some(api)
    api
  }

  val operational_api : consumer_thread_i_Operational_Api = {
    val api = consumer_thread_i_Operational_Api(
      id,
      read_port.id
    )
    consumer_thread_i_consumer_consumer_Bridge.c_operational_api = Some(api)
    api
  }

  val entryPoints : Bridge.EntryPoints =
    consumer_thread_i_consumer_consumer_Bridge.EntryPoints(
      id,

      read_port.id,

      dispatchTriggers,

      initialization_api,
      operational_api)
}

object consumer_thread_i_consumer_consumer_Bridge {

  var c_initialization_api: Option[consumer_thread_i_Initialization_Api] = None()
  var c_operational_api: Option[consumer_thread_i_Operational_Api] = None()

  @datatype class EntryPoints(
    consumer_thread_i_consumer_consumer_BridgeId : Art.BridgeId,
    read_port_Id : Art.PortId,
    dispatchTriggers : Option[ISZ[Art.PortId]],
    initialization_api: consumer_thread_i_Initialization_Api,
    operational_api: consumer_thread_i_Operational_Api) extends Bridge.EntryPoints {

    val dataInPortIds: ISZ[Art.PortId] = IS(read_port_Id)

    val eventInPortIds: ISZ[Art.PortId] = IS()

    val dataOutPortIds: ISZ[Art.PortId] = IS()

    val eventOutPortIds: ISZ[Art.PortId] = IS()

    def initialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: consumer_thread_i_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def compute(): Unit = {
      Art.receiveInput(eventInPortIds, dataInPortIds)

      // implement the following in 'component':  def timeTriggered(api: consumer_thread_i_Operational_Api): Unit = {}
      component.timeTriggered(operational_api)

      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def finalise(): Unit = {
      // implement the following method in 'component':  def finalise(api: consumer_thread_i_Operational_Api): Unit = {}
      component.finalise(operational_api)
    }

    override
    def testInitialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: consumer_thread_i_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }

    override
    def testCompute(): Unit = {
      Art.receiveInput(eventInPortIds, dataInPortIds)

      // implement the following in 'component':  def timeTriggered(api: consumer_thread_i_Operational_Api): Unit = {}
      component.timeTriggered(operational_api)

      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }
  }
}