// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#ifndef SB_PRODUCER_T_I_H
#define SB_PRODUCER_T_I_H

#include <sb_types.h>

bool sb_emit_enqueue(void);

void compute(const int64_t * in_arg);

void init(const int64_t *arg);

#endif // SB_PRODUCER_T_I_H
