#ifndef PRODUCER_THREAD_I_PRODUCER_PRODUCER_API_H
#define PRODUCER_THREAD_I_PRODUCER_PRODUCER_API_H

#include <all.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void api_put_write_port__base_test_data_port_periodic_domains_producer_thread_i_producer_producer(
  STACK_FRAME
  S8 value);

void api_logInfo__base_test_data_port_periodic_domains_producer_thread_i_producer_producer(
  STACK_FRAME
  String str);

void api_logDebug__base_test_data_port_periodic_domains_producer_thread_i_producer_producer(
  STACK_FRAME
  String str);

void api_logError__base_test_data_port_periodic_domains_producer_thread_i_producer_producer(
  STACK_FRAME
  String str);

#endif
