#include <producer_thread_i_producer_producer_api.h>
#include <producer_thread_i_producer_producer.h>

static bool apis_initialized = false;
static struct base_test_data_port_periodic_domains_producer_thread_i_Initialization_Api initialization_api;
static struct base_test_data_port_periodic_domains_producer_thread_i_Operational_Api operational_api;

static void initialize_apis(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "producer_thread_i_producer_producer.c", "", "initialize_apis", 0);

  // Option_B8220B = Option[base.test_data_port_periodic_domains.producer_thread_i_Initialization_Api]
  Option_B8220B_get_(SF (base_test_data_port_periodic_domains_producer_thread_i_Initialization_Api) &initialization_api, base_test_data_port_periodic_domains_producer_thread_i_producer_producer_Bridge_c_initialization_api(SF_LAST));
  // Option_D7201D = Option[base.test_data_port_periodic_domains.producer_thread_i_Operational_Api]
  Option_D7201D_get_(SF (base_test_data_port_periodic_domains_producer_thread_i_Operational_Api) &operational_api, base_test_data_port_periodic_domains_producer_thread_i_producer_producer_Bridge_c_operational_api(SF_LAST));
  apis_initialized = true;
}

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void api_put_write_port__base_test_data_port_periodic_domains_producer_thread_i_producer_producer(
  STACK_FRAME
  S8 value) {
  DeclNewStackFrame(caller, "producer_thread_i_producer_producer_api.c", "", "api_put_write_port__base_test_data_port_periodic_domains_producer_thread_i_producer_producer", 0);

  if(!apis_initialized) { initialize_apis(SF_LAST); }

  base_test_data_port_periodic_domains_producer_thread_i_Initialization_Api_put_write_port_(
    SF
    &initialization_api,
    value);
}

void api_logInfo__base_test_data_port_periodic_domains_producer_thread_i_producer_producer(
  STACK_FRAME
  String str) {
  DeclNewStackFrame(caller, "producer_thread_i_producer_producer_api.c", "", "api_logInfo__base_test_data_port_periodic_domains_producer_thread_i_producer_producer", 0);

  if(!apis_initialized) { initialize_apis(SF_LAST); }

  base_test_data_port_periodic_domains_producer_thread_i_Initialization_Api_logInfo_(
    SF
    &initialization_api,
    str);
}

void api_logDebug__base_test_data_port_periodic_domains_producer_thread_i_producer_producer(
  STACK_FRAME
  String str) {
  DeclNewStackFrame(caller, "producer_thread_i_producer_producer_api.c", "", "api_logDebug__base_test_data_port_periodic_domains_producer_thread_i_producer_producer", 0);

  if(!apis_initialized) { initialize_apis(SF_LAST); }

  base_test_data_port_periodic_domains_producer_thread_i_Initialization_Api_logDebug_(
    SF
    &initialization_api,
    str);
}

void api_logError__base_test_data_port_periodic_domains_producer_thread_i_producer_producer(
  STACK_FRAME
  String str) {
  DeclNewStackFrame(caller, "producer_thread_i_producer_producer_api.c", "", "api_logError__base_test_data_port_periodic_domains_producer_thread_i_producer_producer", 0);

  if(!apis_initialized) { initialize_apis(SF_LAST); }

  base_test_data_port_periodic_domains_producer_thread_i_Initialization_Api_logError_(
    SF
    &initialization_api,
    str);
}

Unit base_test_data_port_periodic_domains_producer_thread_i_producer_producer_initialise(
  STACK_FRAME
  base_test_data_port_periodic_domains_producer_thread_i_Initialization_Api api) {
  DeclNewStackFrame(caller, "producer_thread_i_producer_producer_api.c", "", "base_test_data_port_periodic_domains_producer_thread_i_producer_producer_initialise", 0);

  base_test_data_port_periodic_domains_producer_thread_i_producer_producer_initialise_(SF_LAST);
}

Unit base_test_data_port_periodic_domains_producer_thread_i_producer_producer_finalise(
  STACK_FRAME
  base_test_data_port_periodic_domains_producer_thread_i_Operational_Api api) {
  DeclNewStackFrame(caller, "producer_thread_i_producer_producer_api.c", "", "base_test_data_port_periodic_domains_producer_thread_i_producer_producer_finalise", 0);

  base_test_data_port_periodic_domains_producer_thread_i_producer_producer_finalise_(SF_LAST);
}

Unit base_test_data_port_periodic_domains_producer_thread_i_producer_producer_timeTriggered(
  STACK_FRAME
  base_test_data_port_periodic_domains_producer_thread_i_Operational_Api api) {
  DeclNewStackFrame(caller, "producer_thread_i_producer_producer_api.c", "", "base_test_data_port_periodic_domains_producer_thread_i_producer_producer_timeTriggered", 0);

  base_test_data_port_periodic_domains_producer_thread_i_producer_producer_timeTriggered_(SF_LAST);
}
