#ifndef CONSUMER_T_I_CONSUMER_CONSUMER_API_H
#define CONSUMER_T_I_CONSUMER_CONSUMER_API_H

#include <all.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

bool api_get_consume__base_test_event_port_periodic_domains_consumer_t_i_consumer_consumer(STACK_FRAME_ONLY);

void api_logInfo__base_test_event_port_periodic_domains_consumer_t_i_consumer_consumer(
  STACK_FRAME
  String str);

void api_logDebug__base_test_event_port_periodic_domains_consumer_t_i_consumer_consumer(
  STACK_FRAME
  String str);

void api_logError__base_test_event_port_periodic_domains_consumer_t_i_consumer_consumer(
  STACK_FRAME
  String str);

#endif
