#ifndef TYPES_H
#define TYPES_H

#include <stdint.h>


#define base_test_data_port_periodic_three_domains_RawEthernetMessage_SIZE 4

typedef uint8_t base_test_data_port_periodic_three_domains_RawEthernetMessage [base_test_data_port_periodic_three_domains_RawEthernetMessage_SIZE];

typedef
  struct base_test_data_port_periodic_three_domains_RawEthernetMessage_container{
    base_test_data_port_periodic_three_domains_RawEthernetMessage f;
  } base_test_data_port_periodic_three_domains_RawEthernetMessage_container;

#endif
