// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include <sb_producer_t_i.h>
#include <sb_queue_int8_t_1.h>
#include <string.h>
#include <camkes.h>

void sb_entrypoint_period_producer_t_i(int64_t *in_arg) {
  compute((int64_t *) in_arg);
}

bool sb_write_port_enqueue(const int8_t *data) {
  sb_queue_int8_t_1_enqueue(sb_write_port_queue_1, (int8_t*) data);
  sb_write_port_1_notification_emit();

  return true;
}

/************************************************************************
 *  sb_entrypoint_producer_t_i_producer_producer_initializer:
 *
 * This is the function invoked by an active thread dispatcher to
 * call to a user-defined entrypoint function.  It sets up the dispatch
 * context for the user-defined entrypoint, then calls it.
 *
 ************************************************************************/
void sb_entrypoint_producer_t_i_producer_producer_initializer(const int64_t * in_arg) {
  init((int64_t *) in_arg);
}

void pre_init(void) {
  // initialise data structure for outgoing event data port write_port
  sb_queue_int8_t_1_init(sb_write_port_queue_1);
}

/************************************************************************
 * int run(void)
 * Main active thread function.
 ************************************************************************/
int run(void) {
  {
    int64_t sb_dummy;
    sb_entrypoint_producer_t_i_producer_producer_initializer(&sb_dummy);
  }
  sb_self_pacer_tick_emit();
  for(;;) {
    sb_self_pacer_tock_wait();
    {
      int64_t sb_dummy = 0;
      sb_entrypoint_period_producer_t_i(&sb_dummy);
    }
    sb_self_pacer_tick_emit();
  }
  return 0;
}
