// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#ifndef SB_PRODUCER_THREAD_I_H
#define SB_PRODUCER_THREAD_I_H

#include <sb_types.h>

bool sb_write_port_write(const union_art_DataContent * value);

#endif // SB_PRODUCER_THREAD_I_H
