// #Sireum

package base.test_event_port_periodic_domains

import org.sireum._
import art._
import base._
import base.test_event_port_periodic_domains.{producer_t_i_producer_producer => component}

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@datatype class producer_t_i_producer_producer_Bridge(
  val id: Art.BridgeId,
  val name: String,
  val dispatchProtocol: DispatchPropertyProtocol,
  val dispatchTriggers: Option[ISZ[Art.PortId]],

  emit: Port[art.Empty]
  ) extends Bridge {

  val ports : Bridge.Ports = Bridge.Ports(
    dataIns = ISZ[art.UPort](),

    dataOuts = ISZ[art.UPort](),

    eventIns = ISZ[art.UPort](),

    eventOuts = ISZ[art.UPort](emit)
  )

  val initialization_api : producer_t_i_Initialization_Api = {
    val api = producer_t_i_Initialization_Api(
      id,
      emit.id
    )
    producer_t_i_producer_producer_Bridge.c_initialization_api = Some(api)
    api
  }

  val operational_api : producer_t_i_Operational_Api = {
    val api = producer_t_i_Operational_Api(
      id,
      emit.id
    )
    producer_t_i_producer_producer_Bridge.c_operational_api = Some(api)
    api
  }

  val entryPoints : Bridge.EntryPoints =
    producer_t_i_producer_producer_Bridge.EntryPoints(
      id,

      emit.id,

      dispatchTriggers,

      initialization_api,
      operational_api)
}

object producer_t_i_producer_producer_Bridge {

  var c_initialization_api: Option[producer_t_i_Initialization_Api] = None()
  var c_operational_api: Option[producer_t_i_Operational_Api] = None()

  @datatype class EntryPoints(
    producer_t_i_producer_producer_BridgeId : Art.BridgeId,
    emit_Id : Art.PortId,
    dispatchTriggers : Option[ISZ[Art.PortId]],
    initialization_api: producer_t_i_Initialization_Api,
    operational_api: producer_t_i_Operational_Api) extends Bridge.EntryPoints {

    val dataInPortIds: ISZ[Art.PortId] = IS()

    val eventInPortIds: ISZ[Art.PortId] = IS()

    val dataOutPortIds: ISZ[Art.PortId] = IS()

    val eventOutPortIds: ISZ[Art.PortId] = IS(emit_Id)

    def initialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: producer_t_i_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def compute(): Unit = {
      Art.receiveInput(eventInPortIds, dataInPortIds)

      // implement the following in 'component':  def timeTriggered(api: producer_t_i_Operational_Api): Unit = {}
      component.timeTriggered(operational_api)

      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def finalise(): Unit = {
      // implement the following method in 'component':  def finalise(api: producer_t_i_Operational_Api): Unit = {}
      component.finalise(operational_api)
    }

    override
    def testInitialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: producer_t_i_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }

    override
    def testCompute(): Unit = {
      Art.receiveInput(eventInPortIds, dataInPortIds)

      // implement the following in 'component':  def timeTriggered(api: producer_t_i_Operational_Api): Unit = {}
      component.timeTriggered(operational_api)

      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }
  }
}