// #Sireum

package base.test_data_port_periodic_domains

import org.sireum._
import art.Art
import base._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
@msig trait consumer_thread_i_consumer_consumer_TestApi {

  def BeforeEntrypoint(): Unit = {
    Art.initTest(Arch.top_impl_Instance_consumer_consumer)
  }

  def AfterEntrypoint(): Unit = {
    Art.finalizeTest(Arch.top_impl_Instance_consumer_consumer)
  }

  def testCompute(): Unit = {
    Art.manuallyClearOutput()
    Art.testCompute(Arch.top_impl_Instance_consumer_consumer)
  }

  def testInitialise(): Unit = {
    Art.manuallyClearOutput()
    Art.testInitialise(Arch.top_impl_Instance_consumer_consumer)
  }

  /** helper function to set the values of all input ports.
   * @param read_port payload for data port read_port
   */
  def put_concrete_inputs(read_port : Base_Types.Integer_8): Unit = {
    put_read_port(read_port)
  }


  // setter for in DataPort
  def put_read_port(value : Base_Types.Integer_8): Unit = {
    Art.insertInInfrastructurePort(Arch.top_impl_Instance_consumer_consumer.operational_api.read_port_Id, Base_Types.Integer_8_Payload(value))
  }

}
