// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#ifndef SB_PRODUCER_T_I_H
#define SB_PRODUCER_T_I_H

#include <sb_types.h>

bool sb_write_port_enqueue(const union_art_DataContent *);

#endif // SB_PRODUCER_T_I_H
