// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#ifndef SB_CONSUMER_T_I_H
#define SB_CONSUMER_T_I_H

#include <sb_types.h>

bool sb_consume_dequeue(void);

#endif // SB_CONSUMER_T_I_H
